all:
	./cuda_image_processing > 1.txt	
	./cuda_image_processing > 2.txt	
	./cuda_image_processing > 3.txt	
	./cuda_image_processing > 4.txt	
	./cuda_image_processing > 5.txt	
	./cuda_image_processing > 6.txt	
	./cuda_image_processing > 7.txt	
	./cuda_image_processing > 8.txt	
	./cuda_image_processing > 9.txt	
	./cuda_image_processing > 10.txt	
	
	
